services:
  database:
    container_name: ${PGHOST}
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./backup:/docker-entry-point-initdb.d

  database-client:
    container_name: pgadmin-container
    image: dpage/pgadmin4:6.17
    restart: always
    environment:
      - PGADMIN_DEFAULT_PASSWORD=password${PGADMIN_PASSWORD}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
    volumes:
      - ./pgAdmin/data:/var/lib/pgadmin
    ports:
      - 8080:80
    depends_on:
      - database

  backend:
    container_name: backend-container
    build: .
    restart: always
    environment:
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./:/app
    depends_on:
      - database
    ports:
      - 8000:8000

volumes:
  postgres-db:
